//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstUplatnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otpremnica
    {
        public Otpremnica()
        {
            this.ListaRobes = new HashSet<ListaRobe>();
        }
    
        public int Id { get; set; }
        public System.DateTime Datum { get; set; }
        public string BrojOtpremnice { get; set; }
        public int SifarnikPartnerId { get; set; }
    
        public virtual SifarnikPartner SifarnikPartner { get; set; }
        public virtual ICollection<ListaRobe> ListaRobes { get; set; }
    }
}
