//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstUplatnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class SifarnikPartner
    {
        public SifarnikPartner()
        {
            this.Otpremnicas = new HashSet<Otpremnica>();
        }
    
        public int Id { get; set; }
        public int SifraPartnera { get; set; }
        public string NazivPartnera { get; set; }
        public string Mesto { get; set; }
    
        public virtual ICollection<Otpremnica> Otpremnicas { get; set; }
    }
}
