//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstUplatnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class SifarnikRobe
    {
        public SifarnikRobe()
        {
            this.ListaRobes = new HashSet<ListaRobe>();
        }
    
        public int Id { get; set; }
        public int SifraRobe { get; set; }
        public string NazivRobe { get; set; }
        public string JedinicaMere { get; set; }
        public double JedinicnaCena { get; set; }
    
        public virtual ICollection<ListaRobe> ListaRobes { get; set; }
    }
}
