//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstUplatnica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UplatnicaModelContainer : DbContext
    {
        public UplatnicaModelContainer()
            : base("name=UplatnicaModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SifarnikPartner> SifarnikPartners { get; set; }
        public DbSet<Otpremnica> Otpremnicas { get; set; }
        public DbSet<SifarnikRobe> SifarnikRobes { get; set; }
        public DbSet<ListaRobe> ListaRobes { get; set; }
    }
}
