//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstUplatnica.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOtpremnica")]
    public interface IOtpremnica {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/insertOtpremnicu", ReplyAction="http://tempuri.org/IOtpremnica/insertOtpremnicuResponse")]
        UplatnicaWCFtoDb.Otpremnica insertOtpremnicu(UplatnicaWCFtoDb.Otpremnica u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/insertOtpremnicu", ReplyAction="http://tempuri.org/IOtpremnica/insertOtpremnicuResponse")]
        System.Threading.Tasks.Task<UplatnicaWCFtoDb.Otpremnica> insertOtpremnicuAsync(UplatnicaWCFtoDb.Otpremnica u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/obrisiOtpremnicu", ReplyAction="http://tempuri.org/IOtpremnica/obrisiOtpremnicuResponse")]
        bool obrisiOtpremnicu(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/obrisiOtpremnicu", ReplyAction="http://tempuri.org/IOtpremnica/obrisiOtpremnicuResponse")]
        System.Threading.Tasks.Task<bool> obrisiOtpremnicuAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/updateOtpremnice", ReplyAction="http://tempuri.org/IOtpremnica/updateOtpremniceResponse")]
        bool updateOtpremnice(UplatnicaWCFtoDb.Otpremnica o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/updateOtpremnice", ReplyAction="http://tempuri.org/IOtpremnica/updateOtpremniceResponse")]
        System.Threading.Tasks.Task<bool> updateOtpremniceAsync(UplatnicaWCFtoDb.Otpremnica o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/OtpremnicaList", ReplyAction="http://tempuri.org/IOtpremnica/OtpremnicaListResponse")]
        UplatnicaWCFtoDb.Otpremnica[] OtpremnicaList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/OtpremnicaList", ReplyAction="http://tempuri.org/IOtpremnica/OtpremnicaListResponse")]
        System.Threading.Tasks.Task<UplatnicaWCFtoDb.Otpremnica[]> OtpremnicaListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/otpremnicaImaRobu", ReplyAction="http://tempuri.org/IOtpremnica/otpremnicaImaRobuResponse")]
        bool otpremnicaImaRobu(UplatnicaWCFtoDb.Otpremnica o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/otpremnicaImaRobu", ReplyAction="http://tempuri.org/IOtpremnica/otpremnicaImaRobuResponse")]
        System.Threading.Tasks.Task<bool> otpremnicaImaRobuAsync(UplatnicaWCFtoDb.Otpremnica o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/postojiNazivOtpremniceUBazi", ReplyAction="http://tempuri.org/IOtpremnica/postojiNazivOtpremniceUBaziResponse")]
        bool postojiNazivOtpremniceUBazi(string BrojOtpremnice, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/postojiNazivOtpremniceUBazi", ReplyAction="http://tempuri.org/IOtpremnica/postojiNazivOtpremniceUBaziResponse")]
        System.Threading.Tasks.Task<bool> postojiNazivOtpremniceUBaziAsync(string BrojOtpremnice, int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/SifarnikPartnerList", ReplyAction="http://tempuri.org/IOtpremnica/SifarnikPartnerListResponse")]
        UplatnicaWCFtoDb.SifarnikPartner[] SifarnikPartnerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/SifarnikPartnerList", ReplyAction="http://tempuri.org/IOtpremnica/SifarnikPartnerListResponse")]
        System.Threading.Tasks.Task<UplatnicaWCFtoDb.SifarnikPartner[]> SifarnikPartnerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/SifarnikRobeList", ReplyAction="http://tempuri.org/IOtpremnica/SifarnikRobeListResponse")]
        UplatnicaWCFtoDb.SifarnikRobe[] SifarnikRobeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/SifarnikRobeList", ReplyAction="http://tempuri.org/IOtpremnica/SifarnikRobeListResponse")]
        System.Threading.Tasks.Task<UplatnicaWCFtoDb.SifarnikRobe[]> SifarnikRobeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/SifarnikRobeListById", ReplyAction="http://tempuri.org/IOtpremnica/SifarnikRobeListByIdResponse")]
        UplatnicaWCFtoDb.SifarnikRobe SifarnikRobeListById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/SifarnikRobeListById", ReplyAction="http://tempuri.org/IOtpremnica/SifarnikRobeListByIdResponse")]
        System.Threading.Tasks.Task<UplatnicaWCFtoDb.SifarnikRobe> SifarnikRobeListByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/insertListuRobe", ReplyAction="http://tempuri.org/IOtpremnica/insertListuRobeResponse")]
        void insertListuRobe(UplatnicaWCFtoDb.ListaRobe lrobe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/insertListuRobe", ReplyAction="http://tempuri.org/IOtpremnica/insertListuRobeResponse")]
        System.Threading.Tasks.Task insertListuRobeAsync(UplatnicaWCFtoDb.ListaRobe lrobe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/SifarnikPartnerListById", ReplyAction="http://tempuri.org/IOtpremnica/SifarnikPartnerListByIdResponse")]
        UplatnicaWCFtoDb.SifarnikPartner SifarnikPartnerListById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/SifarnikPartnerListById", ReplyAction="http://tempuri.org/IOtpremnica/SifarnikPartnerListByIdResponse")]
        System.Threading.Tasks.Task<UplatnicaWCFtoDb.SifarnikPartner> SifarnikPartnerListByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/brojRobeNaUplatnici", ReplyAction="http://tempuri.org/IOtpremnica/brojRobeNaUplatniciResponse")]
        int brojRobeNaUplatnici(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/brojRobeNaUplatnici", ReplyAction="http://tempuri.org/IOtpremnica/brojRobeNaUplatniciResponse")]
        System.Threading.Tasks.Task<int> brojRobeNaUplatniciAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/UkupnaCenaRobePoUplatnici", ReplyAction="http://tempuri.org/IOtpremnica/UkupnaCenaRobePoUplatniciResponse")]
        double UkupnaCenaRobePoUplatnici(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/UkupnaCenaRobePoUplatnici", ReplyAction="http://tempuri.org/IOtpremnica/UkupnaCenaRobePoUplatniciResponse")]
        System.Threading.Tasks.Task<double> UkupnaCenaRobePoUplatniciAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/obrisiListuRobeNaOsnovuOtpremniceId", ReplyAction="http://tempuri.org/IOtpremnica/obrisiListuRobeNaOsnovuOtpremniceIdResponse")]
        bool obrisiListuRobeNaOsnovuOtpremniceId(int otpremnicaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/obrisiListuRobeNaOsnovuOtpremniceId", ReplyAction="http://tempuri.org/IOtpremnica/obrisiListuRobeNaOsnovuOtpremniceIdResponse")]
        System.Threading.Tasks.Task<bool> obrisiListuRobeNaOsnovuOtpremniceIdAsync(int otpremnicaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/listaRobePordukata", ReplyAction="http://tempuri.org/IOtpremnica/listaRobePordukataResponse")]
        UplatnicaWCFtoDb.ListaRobe[] listaRobePordukata(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/listaRobePordukata", ReplyAction="http://tempuri.org/IOtpremnica/listaRobePordukataResponse")]
        System.Threading.Tasks.Task<UplatnicaWCFtoDb.ListaRobe[]> listaRobePordukataAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/listaRobeById", ReplyAction="http://tempuri.org/IOtpremnica/listaRobeByIdResponse")]
        UplatnicaWCFtoDb.ListaRobe listaRobeById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/listaRobeById", ReplyAction="http://tempuri.org/IOtpremnica/listaRobeByIdResponse")]
        System.Threading.Tasks.Task<UplatnicaWCFtoDb.ListaRobe> listaRobeByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/OtpremnicaListBasedOnPartnersId", ReplyAction="http://tempuri.org/IOtpremnica/OtpremnicaListBasedOnPartnersIdResponse")]
        UplatnicaWCFtoDb.Otpremnica[] OtpremnicaListBasedOnPartnersId(int partnerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/OtpremnicaListBasedOnPartnersId", ReplyAction="http://tempuri.org/IOtpremnica/OtpremnicaListBasedOnPartnersIdResponse")]
        System.Threading.Tasks.Task<UplatnicaWCFtoDb.Otpremnica[]> OtpremnicaListBasedOnPartnersIdAsync(int partnerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/OtpremnicaListBasedOnDateTime", ReplyAction="http://tempuri.org/IOtpremnica/OtpremnicaListBasedOnDateTimeResponse")]
        UplatnicaWCFtoDb.Otpremnica[] OtpremnicaListBasedOnDateTime(System.DateTime partnerObjDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOtpremnica/OtpremnicaListBasedOnDateTime", ReplyAction="http://tempuri.org/IOtpremnica/OtpremnicaListBasedOnDateTimeResponse")]
        System.Threading.Tasks.Task<UplatnicaWCFtoDb.Otpremnica[]> OtpremnicaListBasedOnDateTimeAsync(System.DateTime partnerObjDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOtpremnicaChannel : ModelFirstUplatnica.ServiceReference1.IOtpremnica, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OtpremnicaClient : System.ServiceModel.ClientBase<ModelFirstUplatnica.ServiceReference1.IOtpremnica>, ModelFirstUplatnica.ServiceReference1.IOtpremnica {
        
        public OtpremnicaClient() {
        }
        
        public OtpremnicaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OtpremnicaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OtpremnicaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OtpremnicaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UplatnicaWCFtoDb.Otpremnica insertOtpremnicu(UplatnicaWCFtoDb.Otpremnica u) {
            return base.Channel.insertOtpremnicu(u);
        }
        
        public System.Threading.Tasks.Task<UplatnicaWCFtoDb.Otpremnica> insertOtpremnicuAsync(UplatnicaWCFtoDb.Otpremnica u) {
            return base.Channel.insertOtpremnicuAsync(u);
        }
        
        public bool obrisiOtpremnicu(int Id) {
            return base.Channel.obrisiOtpremnicu(Id);
        }
        
        public System.Threading.Tasks.Task<bool> obrisiOtpremnicuAsync(int Id) {
            return base.Channel.obrisiOtpremnicuAsync(Id);
        }
        
        public bool updateOtpremnice(UplatnicaWCFtoDb.Otpremnica o) {
            return base.Channel.updateOtpremnice(o);
        }
        
        public System.Threading.Tasks.Task<bool> updateOtpremniceAsync(UplatnicaWCFtoDb.Otpremnica o) {
            return base.Channel.updateOtpremniceAsync(o);
        }
        
        public UplatnicaWCFtoDb.Otpremnica[] OtpremnicaList() {
            return base.Channel.OtpremnicaList();
        }
        
        public System.Threading.Tasks.Task<UplatnicaWCFtoDb.Otpremnica[]> OtpremnicaListAsync() {
            return base.Channel.OtpremnicaListAsync();
        }
        
        public bool otpremnicaImaRobu(UplatnicaWCFtoDb.Otpremnica o) {
            return base.Channel.otpremnicaImaRobu(o);
        }
        
        public System.Threading.Tasks.Task<bool> otpremnicaImaRobuAsync(UplatnicaWCFtoDb.Otpremnica o) {
            return base.Channel.otpremnicaImaRobuAsync(o);
        }
        
        public bool postojiNazivOtpremniceUBazi(string BrojOtpremnice, int Id) {
            return base.Channel.postojiNazivOtpremniceUBazi(BrojOtpremnice, Id);
        }
        
        public System.Threading.Tasks.Task<bool> postojiNazivOtpremniceUBaziAsync(string BrojOtpremnice, int Id) {
            return base.Channel.postojiNazivOtpremniceUBaziAsync(BrojOtpremnice, Id);
        }
        
        public UplatnicaWCFtoDb.SifarnikPartner[] SifarnikPartnerList() {
            return base.Channel.SifarnikPartnerList();
        }
        
        public System.Threading.Tasks.Task<UplatnicaWCFtoDb.SifarnikPartner[]> SifarnikPartnerListAsync() {
            return base.Channel.SifarnikPartnerListAsync();
        }
        
        public UplatnicaWCFtoDb.SifarnikRobe[] SifarnikRobeList() {
            return base.Channel.SifarnikRobeList();
        }
        
        public System.Threading.Tasks.Task<UplatnicaWCFtoDb.SifarnikRobe[]> SifarnikRobeListAsync() {
            return base.Channel.SifarnikRobeListAsync();
        }
        
        public UplatnicaWCFtoDb.SifarnikRobe SifarnikRobeListById(int Id) {
            return base.Channel.SifarnikRobeListById(Id);
        }
        
        public System.Threading.Tasks.Task<UplatnicaWCFtoDb.SifarnikRobe> SifarnikRobeListByIdAsync(int Id) {
            return base.Channel.SifarnikRobeListByIdAsync(Id);
        }
        
        public void insertListuRobe(UplatnicaWCFtoDb.ListaRobe lrobe) {
            base.Channel.insertListuRobe(lrobe);
        }
        
        public System.Threading.Tasks.Task insertListuRobeAsync(UplatnicaWCFtoDb.ListaRobe lrobe) {
            return base.Channel.insertListuRobeAsync(lrobe);
        }
        
        public UplatnicaWCFtoDb.SifarnikPartner SifarnikPartnerListById(int Id) {
            return base.Channel.SifarnikPartnerListById(Id);
        }
        
        public System.Threading.Tasks.Task<UplatnicaWCFtoDb.SifarnikPartner> SifarnikPartnerListByIdAsync(int Id) {
            return base.Channel.SifarnikPartnerListByIdAsync(Id);
        }
        
        public int brojRobeNaUplatnici(int Id) {
            return base.Channel.brojRobeNaUplatnici(Id);
        }
        
        public System.Threading.Tasks.Task<int> brojRobeNaUplatniciAsync(int Id) {
            return base.Channel.brojRobeNaUplatniciAsync(Id);
        }
        
        public double UkupnaCenaRobePoUplatnici(int Id) {
            return base.Channel.UkupnaCenaRobePoUplatnici(Id);
        }
        
        public System.Threading.Tasks.Task<double> UkupnaCenaRobePoUplatniciAsync(int Id) {
            return base.Channel.UkupnaCenaRobePoUplatniciAsync(Id);
        }
        
        public bool obrisiListuRobeNaOsnovuOtpremniceId(int otpremnicaId) {
            return base.Channel.obrisiListuRobeNaOsnovuOtpremniceId(otpremnicaId);
        }
        
        public System.Threading.Tasks.Task<bool> obrisiListuRobeNaOsnovuOtpremniceIdAsync(int otpremnicaId) {
            return base.Channel.obrisiListuRobeNaOsnovuOtpremniceIdAsync(otpremnicaId);
        }
        
        public UplatnicaWCFtoDb.ListaRobe[] listaRobePordukata(int Id) {
            return base.Channel.listaRobePordukata(Id);
        }
        
        public System.Threading.Tasks.Task<UplatnicaWCFtoDb.ListaRobe[]> listaRobePordukataAsync(int Id) {
            return base.Channel.listaRobePordukataAsync(Id);
        }
        
        public UplatnicaWCFtoDb.ListaRobe listaRobeById(int Id) {
            return base.Channel.listaRobeById(Id);
        }
        
        public System.Threading.Tasks.Task<UplatnicaWCFtoDb.ListaRobe> listaRobeByIdAsync(int Id) {
            return base.Channel.listaRobeByIdAsync(Id);
        }
        
        public UplatnicaWCFtoDb.Otpremnica[] OtpremnicaListBasedOnPartnersId(int partnerId) {
            return base.Channel.OtpremnicaListBasedOnPartnersId(partnerId);
        }
        
        public System.Threading.Tasks.Task<UplatnicaWCFtoDb.Otpremnica[]> OtpremnicaListBasedOnPartnersIdAsync(int partnerId) {
            return base.Channel.OtpremnicaListBasedOnPartnersIdAsync(partnerId);
        }
        
        public UplatnicaWCFtoDb.Otpremnica[] OtpremnicaListBasedOnDateTime(System.DateTime partnerObjDate) {
            return base.Channel.OtpremnicaListBasedOnDateTime(partnerObjDate);
        }
        
        public System.Threading.Tasks.Task<UplatnicaWCFtoDb.Otpremnica[]> OtpremnicaListBasedOnDateTimeAsync(System.DateTime partnerObjDate) {
            return base.Channel.OtpremnicaListBasedOnDateTimeAsync(partnerObjDate);
        }
    }
}
