#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UplatnicaWCFtoDb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OtpremnicaDatabase")]
	public partial class UplatnicaLinqDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOtpremnica(Otpremnica instance);
    partial void UpdateOtpremnica(Otpremnica instance);
    partial void DeleteOtpremnica(Otpremnica instance);
    #endregion
		
		public UplatnicaLinqDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OtpremnicaDatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UplatnicaLinqDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UplatnicaLinqDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UplatnicaLinqDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UplatnicaLinqDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Otpremnica> Otpremnicas
		{
			get
			{
				return this.GetTable<Otpremnica>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Otpremnicas")]
	public partial class Otpremnica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _Datum;
		
		private string _BrojOtpremnice;
		
		private int _SifarnikPartnerId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDatumChanging(System.DateTime value);
    partial void OnDatumChanged();
    partial void OnBrojOtpremniceChanging(string value);
    partial void OnBrojOtpremniceChanged();
    partial void OnSifarnikPartnerIdChanging(int value);
    partial void OnSifarnikPartnerIdChanged();
    #endregion
		
		public Otpremnica()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="DateTime NOT NULL")]
		public System.DateTime Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this.OnDatumChanging(value);
					this.SendPropertyChanging();
					this._Datum = value;
					this.SendPropertyChanged("Datum");
					this.OnDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrojOtpremnice", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string BrojOtpremnice
		{
			get
			{
				return this._BrojOtpremnice;
			}
			set
			{
				if ((this._BrojOtpremnice != value))
				{
					this.OnBrojOtpremniceChanging(value);
					this.SendPropertyChanging();
					this._BrojOtpremnice = value;
					this.SendPropertyChanged("BrojOtpremnice");
					this.OnBrojOtpremniceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifarnikPartnerId", DbType="Int NOT NULL")]
		public int SifarnikPartnerId
		{
			get
			{
				return this._SifarnikPartnerId;
			}
			set
			{
				if ((this._SifarnikPartnerId != value))
				{
					this.OnSifarnikPartnerIdChanging(value);
					this.SendPropertyChanging();
					this._SifarnikPartnerId = value;
					this.SendPropertyChanged("SifarnikPartnerId");
					this.OnSifarnikPartnerIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
