#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UplatnicaWCFtoDb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OtpremnicaDatabase")]
	public partial class SifarnikRobeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSifarnikRobe(SifarnikRobe instance);
    partial void UpdateSifarnikRobe(SifarnikRobe instance);
    partial void DeleteSifarnikRobe(SifarnikRobe instance);
    #endregion
		
		public SifarnikRobeDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OtpremnicaDatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SifarnikRobeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SifarnikRobeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SifarnikRobeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SifarnikRobeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SifarnikRobe> SifarnikRobes
		{
			get
			{
				return this.GetTable<SifarnikRobe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SifarnikRobes")]
	public partial class SifarnikRobe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _SifraRobe;
		
		private string _NazivRobe;
		
		private string _JedinicaMere;
		
		private double _JedinicnaCena;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSifraRobeChanging(int value);
    partial void OnSifraRobeChanged();
    partial void OnNazivRobeChanging(string value);
    partial void OnNazivRobeChanged();
    partial void OnJedinicaMereChanging(string value);
    partial void OnJedinicaMereChanged();
    partial void OnJedinicnaCenaChanging(double value);
    partial void OnJedinicnaCenaChanged();
    #endregion
		
		public SifarnikRobe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SifraRobe", DbType="Int NOT NULL")]
		public int SifraRobe
		{
			get
			{
				return this._SifraRobe;
			}
			set
			{
				if ((this._SifraRobe != value))
				{
					this.OnSifraRobeChanging(value);
					this.SendPropertyChanging();
					this._SifraRobe = value;
					this.SendPropertyChanged("SifraRobe");
					this.OnSifraRobeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazivRobe", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NazivRobe
		{
			get
			{
				return this._NazivRobe;
			}
			set
			{
				if ((this._NazivRobe != value))
				{
					this.OnNazivRobeChanging(value);
					this.SendPropertyChanging();
					this._NazivRobe = value;
					this.SendPropertyChanged("NazivRobe");
					this.OnNazivRobeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JedinicaMere", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string JedinicaMere
		{
			get
			{
				return this._JedinicaMere;
			}
			set
			{
				if ((this._JedinicaMere != value))
				{
					this.OnJedinicaMereChanging(value);
					this.SendPropertyChanging();
					this._JedinicaMere = value;
					this.SendPropertyChanged("JedinicaMere");
					this.OnJedinicaMereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JedinicnaCena", DbType="Float NOT NULL")]
		public double JedinicnaCena
		{
			get
			{
				return this._JedinicnaCena;
			}
			set
			{
				if ((this._JedinicnaCena != value))
				{
					this.OnJedinicnaCenaChanging(value);
					this.SendPropertyChanging();
					this._JedinicnaCena = value;
					this.SendPropertyChanged("JedinicnaCena");
					this.OnJedinicnaCenaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
