<?xml version="1.0" encoding="utf-8"?><Database Name="OtpremnicaDatabase" Class="SifarnikPartnerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DANIEL\SQLEXPRESS;Initial Catalog=OtpremnicaDatabase;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OtpremnicaDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SifarnikPartners" Member="SifarnikPartners">
    <Type Name="SifarnikPartner">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SifraPartnera" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NazivPartnera" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Mesto" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>